"""Embeds the firmware's own source into the firmware.

Runs as a PlatformIO pre-step (extra_scripts = pre:embed_source.py): before
every build, src/source_embed.h is regenerated from the sources. The USB
command `src` therefore prints exactly the source the running firmware was
built from -- a divergence cannot arise in the first place, because nobody has
to remember to redo the embedding by hand.

The reason: the state flashed on 19 Aug 2026 existed only as a working copy in
/home/gh/e22pico and in no commit. On the device itself it can no longer be
lost.

Everything in src/ is embedded except the generated source_embed.h itself and
lorawan_secret.h -- the AppKey is not supposed to come out of the USB console
via `src`. New source files therefore end up in the flash on their own, nobody
has to maintain a list.
"""
import os

# PlatformIO runs pre-steps through SCons, where there is no __file__ -- the
# project path then comes from the build environment. Called by hand, the
# second path applies, so source_embed.h can also be generated without pio.
try:
    Import("env")  # noqa: F821 -- provided by SCons
    HERE = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")
TARGET = os.path.join(SRC, "source_embed.h")
# Delimiter of the raw string literal. It must not occur in the source -- this
# is checked below, otherwise the literal falls apart and the build dies with a
# cryptic error.
DELIMITER = "SOURCE"
# Not embedded: the generated file itself (it would grow with every build) and
# the AppKey.
EXCLUDED = {"source_embed.h", "lorawan_secret.h"}


def sources():
    """All source files in src/, in a fixed order."""
    return sorted(d for d in os.listdir(SRC)
                  if d.endswith((".cpp", ".h")) and d not in EXCLUDED)


def generate():
    parts = [
        "// GENERATED by embed_source.py -- do not edit by hand.",
        "// Changes belong in the sources in src/; the next build regenerates",
        "// this file from them.",
        "",
        "#ifndef SOURCE_EMBED_H",
        "#define SOURCE_EMBED_H",
        "",
    ]
    files = sources()
    for i, name in enumerate(files):
        with open(os.path.join(SRC, name), encoding="utf-8") as f:
            text = f.read()
        if ')%s"' % DELIMITER in text:
            raise SystemExit("%s contains the delimiter -- literal would break" % name)
        parts.append('static const char SOURCE_%d[] = R"%s(%s)%s";' % (i, DELIMITER, text, DELIMITER))
        parts.append("")
    parts.append("#define SOURCE_COUNT %d" % len(files))
    parts.append("static const char *const SOURCE_NAMES[] = {%s};"
                 % ", ".join('"%s"' % d for d in files))
    parts.append("static const char *const SOURCE_TEXTS[] = {%s};"
                 % ", ".join("SOURCE_%d" % i for i in range(len(files))))
    parts += ["", "#endif // SOURCE_EMBED_H", ""]
    new = "\n".join(parts)

    # Only write when something changed -- otherwise PlatformIO rebuilds
    # everything on every call because the file's timestamp jumps.
    old = None
    if os.path.exists(TARGET):
        with open(TARGET, encoding="utf-8") as f:
            old = f.read()
    if old != new:
        with open(TARGET, "w") as f:
            f.write(new)
        print("source_embed.h regenerated (%d files, %d bytes embedded)"
              % (len(files), sum(os.path.getsize(os.path.join(SRC, d)) for d in sources())))
    else:
        print("source_embed.h unchanged")


generate()
